version: '3.7'

services:
 mysql:
    image: mysql:5.7
    container_name: mysql-5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'shesha'
      MYSQL_USER: 'sample'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql

 redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_volume:/data

 auth:
    build: ./auth_scaling
    container_name: auth
    ports:
      - "4000:7000"
    environment:
      - SALT=10
      - OTP_VALID_TIME=300
      - REDIS_HOST=redis
      - SQL_HOST=mysql    # Connect to the MySQL service using its container name
      - SQL_USER=root
      - SQL_PASSWORD=password
      - SQL_DB=shesha
      - PORT=7000
      - EMAIL=covaitraveller@gmail.com
      - PASSWORD="ghzn uprx hzdt xohh"
      - SECRET="qwertyuiopasdfghjklzxrtyuioasdfghjpasdfghjklzxcvbnmwertyuioasdfghjnmwertyuioasdfghj"
    depends_on:
      - mysql
      - redis
    command: ["/bin/sh", "-c", "while ! nc -z mysql 3306; do sleep 1; done; npm start"]  

volumes:
 mysql-db:
 redis_volume:
